multimediawerk/urls.py
from django.urls import path
from . import views

app_name = 'multimediawerk'
urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("angebote", views.AngebotList.as_view(), name="angebot"),
    path("angebot/<int:pk>", views.AngebotDetail.as_view(), name="angebot_detail"),
    path("referenzen", views.ReferenzenView.as_view(), name="referenzen"),
    path("ueber-uns", views.AboutView.as_view(), name="about"),
    path("blog", views.Blogposts.as_view(), name="blog"),
    path("angebot/<int:angebot_id>/preisplan/<int:preisplan_id>/contact",
         views.AngebotContact.as_view(), name="angebot_message"),
    path("angebot/<int:angebot_id>/preisplan/<int:preisplan_id>/message/<int:message_id>",
         views.AngebotSuccessMessage.as_view(), name="angebot_success_message"),
    path("kontakt", views.Contact.as_view(), name="contact_message"),
    path("kontakt/message/<int:message_id>",
         views.ContactSuccessMessage.as_view(), name="contact_success_message")
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('multimediawerk.urls')),
    path('admin/', admin.site.urls),
]

multimediawerk/models.py
from django.db import models

# Create your models here.


class Angebot(models.Model):
    order = models.IntegerField("Order", default=1)
    name = models.CharField(
        "Angebot Name", max_length=100, default="Angebotname")
    subtitel = models.CharField("Subtitel", max_length=100, default="Subtitel")
    kurzbeschrieb = models.TextField("Kurzbeschrieb", default="Kurzbeschrieb")
    bild = models.CharField("Bild", max_length=100, default="gis.webp")
    video = models.CharField(
        'Video Name (aus static Ordner)', max_length=50, blank=True)
    cards_titel = models.CharField(
        "Angebot Cards Titel", max_length=100, default="Angebot Cards Titel")
    cards_beschrieb = models.TextField(
        "Angebot Cards Beschrieb", default="Angebot Cards Beschrieb")
    cards = models.ManyToManyField("Card", blank=True)
    preise = models.ManyToManyField("Preisplan", blank=True)

    class Meta:
        verbose_name_plural = "Angebote"
        ordering = ["order"]

    def __str__(self):
        return self.name


class Referenz(models.Model):
    titel = models.CharField("Titel", max_length=100, default="Title")
    kurzbeschrieb = models.TextField("Kurzbeschrieb", default="Kurzbeschrieb")
    bild = models.CharField("Bild", max_length=50, blank=True)
    video = models.CharField("Video ID", max_length=50, blank=True)
    angebot = models.ForeignKey("Angebot", on_delete=models.CASCADE)
    stakeholder = models.ForeignKey(
        "Stakeholder", on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = "Referenzen"

    def __str__(self):
        return self.titel


class Card(models.Model):
    titel = models.CharField("Titel", max_length=100, default="Titel")
    subtitel = models.TextField("Subtitel", default="Subtitel")
    metadaten = models.TextField("Metadaten", blank=True)
    kurzbeschrieb = models.TextField("Kurzbeschrieb", default="Kurzbeschrieb")
    video = models.CharField('Video ID', max_length=50, blank=True)
    bild = models.CharField('Bild ID', max_length=50, default="gis.webp")

    class Meta:
        verbose_name_plural = "Cards"

    def __str__(self):
        return self.titel


class Preisplan(models.Model):
    order = models.IntegerField("Order", default=1)
    name = models.CharField("Name", max_length=50, default="Preisplan Name")
    preis = models.CharField("Preis", max_length=50)
    einheit = models.CharField("Einheit", max_length=50)
    popular = models.BooleanField("Populär", default=False)
    features = models.ManyToManyField("Preisplanfeature", blank=True)

    class Meta:
        verbose_name_plural = "Preispläne"
        ordering = ['order']

    def __str__(self):
        return self.name


class Preisplanfeature(models.Model):
    name = models.CharField("Titel", max_length=100)
    aktiv = models.BooleanField("Aktiv", default=True)

    class Meta:
        verbose_name_plural = "Preisplan Features"

    def __str__(self):
        return self.name + " | aktiv = " + str(self.aktiv)


class Testimonial(models.Model):
    text = models.TextField("Testimonial Text")
    angebot = models.ForeignKey("Angebot", on_delete=models.CASCADE)
    stakeholder = models.ForeignKey(
        "Stakeholder", on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = "Testimonials"

    def __str__(self):
        return self.text


class Stakeholder(models.Model):
    logo = models.CharField("Logo", max_length=100)
    firma = models.CharField("Firma", max_length=100)
    name = models.CharField("Name", max_length=50)
    vorname = models.CharField("Vorname", max_length=50)
    position = models.CharField("Position", max_length=100)

    class Meta:
        verbose_name_plural = "Stakeholders"

    def __str__(self):
        return self.firma + ", " + self.name + " " + self.vorname


class Blogpost(models.Model):
    titel = models.CharField("Title", max_length=100)
    kurzbeschrieb = models.TextField("Kurzbeschrieb")
    datum = models.DateField("Publizierungsdatum")
    teaser_img = models.CharField("Vorschaubild", max_length=100)
    verfasser = models.ForeignKey("Stakeholder", on_delete=models.CASCADE)
    url = models.URLField("URL zum Post")

    class Meta:
        verbose_name_plural = "Blogposts"

    def __str__(self):
        return self.titel


class AngebotMessage(models.Model):
    name = models.CharField("Name", max_length=100)
    vorname = models.CharField("Vorname", max_length=100)
    email = models.EmailField("E-Mail")
    nachricht = models.TextField("Nachricht", blank=True)
    datum = models.DateField("Publizierungsdatum")
    angebot = models.ForeignKey("Angebot", on_delete=models.CASCADE)
    preisplan = models.ForeignKey("Preisplan", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Angebot Nachrichten"

    def __str__(self):
        return str(self.datum) + ": " + self.name + " " + self.vorname


class ContactMessage(models.Model):
    name = models.CharField("Name", max_length=100)
    vorname = models.CharField("Vorname", max_length=100)
    email = models.EmailField("E-Mail")
    nachricht = models.TextField("Nachricht", blank=True)
    datum = models.DateField("Publizierungsdatum")

    class Meta:
        verbose_name_plural = "Kontakt Nachrichten"

    def __str__(self):
        return str(self.datum) + ": " + self.name + " " + self.vorname

multimediawerk/forms.py
from django.forms import ModelForm, TextInput, Textarea, EmailInput
from .models import AngebotMessage, ContactMessage


class AngebotMessageForm(ModelForm):
    class Meta:
        model = AngebotMessage
        fields = ['name', 'vorname', 'email', 'nachricht']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'vorname': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),
            'nachricht': Textarea(attrs={'class': 'form-control', 'rows': 5})
        }


class ContactMessageForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'vorname', 'email', 'nachricht']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'vorname': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),
            'nachricht': Textarea(attrs={'class': 'form-control', 'rows': 5})
        }

multimediawerk/views.py
from django.views.generic import ListView, TemplateView, DetailView, CreateView
from django.urls import reverse
from django.core.mail import send_mail
from django.shortcuts import render
from datetime import datetime
from .models import Angebot, Blogpost, Referenz, Preisplan, AngebotMessage, ContactMessage
from .forms import ContactMessageForm, AngebotMessageForm
from decouple import config
# Create your views here.


class HomeView(TemplateView):
    template_name = "multimediawerk/index.html"


class AngebotList(ListView):
    model = Angebot
    template_name = "multimediawerk/angebote.html"
    context_object_name = "angebote"


class AngebotDetail(DetailView):
    model = Angebot
    template_name = 'multimediawerk/angebot_detail.html'


class ReferenzenView(ListView):
    model = Referenz
    template_name = "multimediawerk/referenzen.html"
    context_object_name = "referenzen"


class AboutView(TemplateView):
    template_name = "multimediawerk/about.html"


class Blogposts(ListView):
    model = Blogpost
    template_name = "multimediawerk/blogposts.html"
    context_object_name = "blogposts"


class AngebotContact(CreateView):
    template_name = "multimediawerk/angebot_contact.html"
    form_class = AngebotMessageForm

    def get_success_url(self):
        return reverse("multimediawerk:angebot_success_message", kwargs={"preisplan_id": self.object.preisplan.id, "angebot_id": self.object.angebot.id, "message_id": self.object.id})

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["angebot"] = Angebot.objects.get(pk=self.kwargs['angebot_id'])
        context["preisplan"] = Preisplan.objects.get(
            pk=self.kwargs['preisplan_id'])
        return context

    def form_valid(self, form):
        # we have to set some attributes which we do not get from the form
        self.object = form.save(commit=False)
        self.object.angebot = Angebot.objects.get(pk=self.kwargs['angebot_id'])
        self.object.preisplan = Preisplan.objects.get(
            pk=self.kwargs['preisplan_id'])
        self.object.datum = datetime.today()
        self.object.save()
        email_message = "Dies ist eine Nachricht von der Karten-Werk Website. \n \n" \
            + "Datum: " + str(self.object.datum.day) + "."\
            + str(self.object.datum.month) + "." \
            + str(self.object.datum.year) + "\n" \
            + "Produkt: " + self.object.angebot.name + "\n" \
            + "Preisplan: " + self.object.preisplan.name + "\n \n" \
            + "Name: " + str(form.cleaned_data.get("name")) + "\n"\
            + "Vorname: " + str(form.cleaned_data.get("vorname")) + "\n" \
            + "Email: " + form.cleaned_data.get("email") + "\n \n"\
            + "Nachricht: \n" \
            + form.cleaned_data.get("nachricht")
        try:
            send_mail(
                'Karten-Werk Website',
                email_message,
                'info@karten-werk.ch', ['hkfrei@karten-werk.ch',
                                        form.cleaned_data.get("email")],
                fail_silently=False
            )
        except:
            context = self.get_context_data()
            context["email_error"] = "Es gab einen Fehler beim E-Mail Versand. \n Bitte versuchen sie es nochmals oder treten sie telefonisch mit uns in Kontakt."
            return render(self.request, template_name=self.template_name, context=context)

        return super().form_valid(form)


class Contact(CreateView):
    template_name = "multimediawerk/contact.html"
    form_class = ContactMessageForm

    def get_success_url(self):
        return reverse("multimediawerk:contact_success_message", kwargs={"message_id": self.object.id})

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["GOOGLE_MAPS_API_KEY"] = config("GOOGLE_MAPS_API_KEY")
        return context

    def form_valid(self, form):
        # we have to set some attributes which we do not get from the form
        self.object = form.save(commit=False)
        self.object.datum = datetime.today()
        self.object.save()
        email_message = "Dies ist eine Nachricht von der Karten-Werk Website. \n \n" \
            + "Datum: " + str(self.object.datum.day) + "."\
            + str(self.object.datum.month) + "." \
            + str(self.object.datum.year) + "\n" \
            + "Name: " + str(form.cleaned_data.get("name")) + "\n"\
            + "Vorname: " + str(form.cleaned_data.get("vorname")) + "\n" \
            + "Email: " + form.cleaned_data.get("email") + "\n \n"\
            + "Nachricht: \n" \
            + form.cleaned_data.get("nachricht")
        try:
            send_mail(
                'Karten-Werk Website',
                email_message,
                'info@karten-werk.ch', ['hkfrei@karten-werk.ch',
                                        form.cleaned_data.get("email")],
                fail_silently=False
            )
        except:
            context = self.get_context_data()
            context["email_error"] = "Es gab einen Fehler beim E-Mail Versand. \n Bitte versuchen sie es nochmals oder treten sie telefonisch mit uns in Kontakt."
            return render(self.request, template_name=self.template_name, context=context)

        return super().form_valid(form)


class AngebotSuccessMessage(TemplateView):
    template_name = "multimediawerk/angebot_success_message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["message"] = AngebotMessage.objects.get(
            pk=self.kwargs["message_id"])
        return context

    def get_success_url(self):
        message = AngebotMessage.objects.get(pk=self.kwargs["message_id"])
        return reverse("multimediawerk:angebot_detail", kwargs={"pk": message.angebot.id})


class ContactSuccessMessage(TemplateView):
    template_name = "multimediawerk/contact_success_message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["message"] = ContactMessage.objects.get(
            pk=self.kwargs["message_id"])
        return context

    def get_success_url(self):
        return reverse("multimediawerk:index")

multimediawerk/templates/multimediawerk/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="keywords"
      content="Massgeschneiderte Webdesign-Lösungen, Umfassende Content-Strategie, Professionelle Bearbeitung von Bildern und Videos, Responsive Webdesign, Videoproduktion für Events, Logo-Design für Start-ups, Technische SEO-Optimierung, Website-Wartung und -Support" />
    <!-- Google Tag Manager -->
    <script>
      ;(function (w, d, s, l, i) {
        w[l] = w[l] || []
        w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" })
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != "dataLayer" ? "&l=" + l : ""
        j.async = true
        j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl
        f.parentNode.insertBefore(j, f)
      })(window, document, "script", "dataLayer", "GTM-MFS8HQQ")
    </script>
    <!-- End Google Tag Manager -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="dark light" />
    <meta
      name="description"
      content="Multimedia-Werk, der One-Stop-Shop für digitale Lösungen" />
    <title>{% block title %}Karten-Werk GmbH{% endblock %}</title>

    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'multimediawerk/img/icon/favicon.ico' %}" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'multimediawerk/css/reset.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'multimediawerk/css/main.css' %}" />
  </head>

  <!-- Google tag (gtag.js) -->
  <script
    async
    src="https://www.googletagmanager.com/gtag/js?id=G-KHJ3DP7LYH"></script>
  <script>
    window.dataLayer = window.dataLayer || []
    function gtag() {
      dataLayer.push(arguments)
    }
    gtag("js", new Date())

    gtag("config", "G-KHJ3DP7LYH")
  </script>

  <body>
    <div class="button-box"></div>

    <header class="site-head" role="banner">
      <a href="#main-content" class="skip-link">Skip to content</a>
      {% block bordertop %}{% endblock %}
      <div class="wrapper">
        <div class="site-head__inner">
          <a
            href="/"
            aria-label="Multimedia-Werk home"
            class="site-head__brand">
            <img
              class="logo-navbar"
              id="logo-navbar"
              src="{% static 'multimediawerk/img/Logo_script.webp' %}"
              alt="" />
          </a>
          <burger-menu max-width="600">
            <nav class="navigation" aria-label="primary">
              <ul role="list">
                <li>
                  <a href="{% url 'multimediawerk:index' %}">Home</a>
                </li>
                <li>
                  <a href="{% url 'multimediawerk:angebot' %}">Angebote</a>
                </li>

                <li>
                  <a href="{% url 'multimediawerk:about' %}">Über uns</a>
                </li>
                <li>
                  <a href="{% url 'multimediawerk:contact_message' %}"
                    >Kontakt</a
                  >
                </li>
              </ul>
            </nav>
          </burger-menu>
        </div>
      </div>
    </header>
    <div class="waves"></div>
    <!-- <figure class="main-svg"></figure> -->
    <div id="content">{% block content %}{% endblock %}</div>
    <footer>
      {% block borderbottom %}{% endblock %}
      <div class="container">
        <div class="content__footer">
          <div class="profil">
            <img
              class="logo-footer"
              src="{% static 'multimediawerk/img/Logo_script_2Z.webp' %}"
              alt="" />
            <div class="logo__area">
              <!-- <span class="logo__name"
                >Multimedia-Werk GmbH <br />Böschacherstrasse 82 <br />8624 Grüt
              </span> -->
            </div>

            <div class="social__media">
              <a
                href="https://github.com/DavidCameronSchaer"
                aria-label="Github Seite David Schaer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  fill="#f2f2f2"
                  class="social-icons"
                  viewBox="0 0 16 16">
                  <path
                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                </svg>
              </a>
              <a
                href="https://www.linkedin.com/in/david-schaer-28a323211/"
                aria-label="LinkedIn Seite von David Schaer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  fill="#f2f2f2"
                  class="social-icons"
                  viewBox="0 0 16 16">
                  <path
                    d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                </svg>
              </a>
              <a
                href="https://twitter.com/"
                aria-label="Twitter Seite von David Schaer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  fill="#f2f2f2"
                  class="social-icons"
                  viewBox="0 0 16 16">
                  <path
                    d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                </svg>
              </a>
              <a
                href="https://www.youtube.com/@davidschaer"
                aria-label="Youtube Seite von David Schaer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  fill="#f2f2f2"
                  class="social-icons"
                  viewBox="0 0 16 16">
                  <path
                    d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
                </svg>
              </a>
            </div>
          </div>
          <div class="nav__area">
            <ul class="nav__header">
              <li class="nav__name">Angebot</li>
              <li>
                <a href="{% url 'multimediawerk:angebot_detail' 1 %}"
                  >Content Creation</a
                >
              </li>
              <li>
                <a href="{% url 'multimediawerk:angebot_detail' 2 %}"
                  >Photo- und Videographie</a
                >
              </li>
              <!-- <li>
                <a href="{% url 'multimediawerk:angebot_detail' 3 %}"
                  >Drohnenbefliegung</a
                >
              </li>
              <li>
                <a href="{% url 'multimediawerk:angebot_detail' 4 %}"
                  >GIS Support</a
                >
              </li> -->
            </ul>
            <ul class="nav__header">
              <li class="nav__name">Company</li>
              <li><a href="#">About</a></li>
              <!-- <li>
                <a href="{% url 'multimediawerk:blog' %}">Blog</a>
              </li> -->
              <li>
                <a href="{% url 'multimediawerk:contact_message' %}">Kontakt</a>
              </li>
            </ul>
          </div>
        </div>
        <hr />
        <div class="footer__bottom">
          <div class="copy__right">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="#f2f2f2"
              class="icon-copyright"
              viewBox="0 0 16 16">
              <path
                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM8.146 4.992c.961 0 1.641.633 1.729 1.512h1.295v-.088c-.094-1.518-1.348-2.572-3.03-2.572-2.068 0-3.269 1.377-3.269 3.638v1.073c0 2.267 1.178 3.603 3.27 3.603 1.675 0 2.93-1.02 3.029-2.467v-.093H9.875c-.088.832-.75 1.418-1.729 1.418-1.224 0-1.927-.891-1.927-2.461v-1.06c0-1.583.715-2.503 1.927-2.503Z" />
            </svg>
            <span>powered by Karten-Werk GmbH</span>
          </div>
        </div>
      </div>
    </footer>
    <script
      type="module"
      src="{% static 'multimediawerk/js/burgerMenu.mjs' %}"></script>
    <!-- Google Tag Manager (noscript) -->
    <noscript
      ><iframe
        src="https://www.googletagmanager.com/ns.html?id=GTM-MFS8HQQ"
        height="0"
        width="0"
        style="display: none; visibility: hidden"></iframe
    ></noscript>
    <!-- End Google Tag Manager (noscript) -->
  </body>
</html>

multimediawerk/templates/multimediawerk/index.html
<!-- prettier-ignore -->

{% extends "multimediawerk/base.html" %} 

{% block title %} Index {% endblock %} 
{% block bordertop %}
<div class="site-head__bordertop-default"></div>
{% endblock %} {% block content %} {% load static %}

<!-- Google tag (gtag.js) -->
<script
  async
  src="https://www.googletagmanager.com/gtag/js?id=G-KHJ3DP7LYH"></script>
<script>
  window.dataLayer = window.dataLayer || []
  function gtag() {
    dataLayer.push(arguments)
  }
  gtag("js", new Date())

  gtag("config", "G-KHJ3DP7LYH")
</script>

<header>
  <h1 class="heading-main">Multimedia-Werk.</h1>
  <h2 class="sub__heading-main">Der One-Stop-Shop für digitale Lösungen.</h2>
</header>

<main>
  <section class="hero">
    <div class="hero-container">
      <div class="hero-content">
        <h3 class="sub__heading">
          Photo- und Videographie | Content Creation | Webdesign
        </h3>
        <p>
          Herzlich Willkommen bei Multimedia-Werk, Ihrem One-Stop-Shop für
          digitale Lösungen! Wir sind ein kleines aber feines Team bestehend aus
          einem GIS- und Webmapping-Spezialisten und einem Content Creator und
          bieten eine massgeschneiderte Palette von Dienstleistungen, um Ihre
          Online-Präsenz zu optimieren.
        </p>
        <div class="button-container-main">
          <a
            href="{% url 'multimediawerk:contact_message' %}"
            class="button button-primary"
            >Kontakt</a
          >
          <a
            href="{% url 'multimediawerk:angebot' %}"
            class="button button-primary"
            >Angebote</a
          >
        </div>
      </div>
      <div class="hero-img">
        <img
          src="{% static 'multimediawerk/img/Herosection_Mainpicture.webp' %}"
          alt="" />
      </div>
    </div>
  </section>
</main>
{% endblock %} {% block borderbottom %}
<div class="site-head__bordertop-default"></div>
{% endblock %}